name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Application/**'
env:
  registryName: "cst31devopsreg.azurecr.io"
  repositoryName: "wth/dotnetcoreapp"
  dockerFolderPath: "Application/src/RazorPagesTestSample"
  tag: "${{github.run_number}}"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore
    - name: Test
      run: dotnet test Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-build --verbosity normal
  containerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ACR login
      run: docker login $registryName -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
    - name: Docker build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker push
      run: docker push $registryName/$repositoryName:$tag
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'cst31devops-dev'
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: $registryName/$repositoryName:$tag
