name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Application/**'
env:
  registryName: "cst31devopsreg.azurecr.io"
  repositoryName: "wth/dotnetcoreapp"
  dockerFolderPath: "Application/aspnet-core-dotnet-core"
  tag: "${{github.run_number}}"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore
    - name: Test
      run: dotnet test Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-build --verbosity normal
  containerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ACR login
      run: docker $registryName -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
    - name: Docker build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker push
      run: docker push $registryName/$repositoryName:$tag
    
